#YAML 是专门用来写配置文件的语言，非常简洁和强大，远比 JSON 格式方便。
#参考文档： http://www.ruanyifeng.com/blog/2016/07/yaml.html

server:
  port: 8080

xiao:
  number: ${random.int}
  hello: xiao哈行哈
  msg: hi,hello world! ${xiao.hello} ${xiao.number}

# 增加xxl-job 的配置文件
xxl.job:
  admin:
    addresses: http://192.168.2.116:38080/xxl-job-admin
  accessToken:
  executor:
    appname: xxl-job-executor-sample-beta
    port: 19999
    logpath: /data/applogs/xxl-job/jobhandler
    logretentiondays: -1
    ip:
